Repository statisticsnorway/dapla-statbank-client, pull requests merged in 2025-05, with the labels that each got.

#213 extend timeout to match that of API
  src/statbank/transfer.py
Labels: bug

#214 Handle validation issues - Make sure tests do not reach internet
  src/statbank/__init__.py
  src/statbank/client.py
  src/statbank/get_apidata.py
  src/statbank/transfer.py
  src/statbank/uttrekk.py
  src/statbank/uttrekk_validations.py
  tests/conftest.py
  tests/test_apidata.py
Labels: bug, enhancement, testing

#212 Remove dependency upon `pyjstat` in `apidata()`
  poetry.lock
  pyproject.toml
  src/statbank/get_apidata.py
  src/statbank/response_to_pandas.py
Labels: refactoring

#216 adding ignore_codes to client.validate
  pyproject.toml
  src/statbank/client.py
Labels: enhancement
